version: '3.8'

services:
  netbox: &netbox
    image: netbox:devcontainer-${VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION}
    env_file:
      - env/netbox.env
      - env/postgres.env
      - env/redis.env
      - env/redis-cache.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      redis-cache:
        condition: service_started
    healthcheck:
      test: "curl -f http://localhost:8000/api/ || exit 1"
      interval: 15s
      timeout: 3s
      retries: 5
    volumes:
      - media-files:/opt/netbox/netbox/media:rw
      - reports-files:/opt/netbox/netbox/reports:rw
      - scripts-files:/opt/netbox/netbox/scripts:rw
      - ./plugins:/opt/plugins:rw
      - ./configuration:/opt/netbox/netbox/netbox/configuration:rw

  netbox-worker:
    <<: *netbox
    depends_on:
      netbox:
        condition: service_healthy
    command: /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py rqworker
    healthcheck:
      test: "ps -aux | grep -v grep | grep -q rqworker || exit 1"
      interval: 15s
      timeout: 3s
      start_period: 20s

  netbox-housekeeping:
    <<: *netbox
    depends_on:
      netbox:
        condition: service_healthy
    command: /opt/netbox/housekeeping.sh
    healthcheck:
      test: "ps -aux | grep -v grep | grep -q housekeeping || exit 1"
      interval: 15s
      timeout: 3s

  postgres:
    image: postgres:15-alpine
    env_file: env/postgres.env
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER || exit 1"
      interval: 5s
      timeout: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    env_file: env/redis.env
    command: sh -c "redis-server --appendonly yes --requirepass \"$$REDIS_PASSWORD\""
    volumes:
      - redis-data:/data

  redis-cache:
    image: redis:7-alpine
    env_file: env/redis-cache.env
    command: sh -c "redis-server --requirepass \"$$REDIS_CACHE_PASSWORD\""
    volumes:
      - redis-cache-data:/data

volumes:
  media-files:
    driver: local
  reports-files:
    driver: local
  scripts-files:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local
  redis-cache-data:
    driver: local
