version: '3.8'

services:
  netbox-devcontainer:
    image: netbox:devcontainer-${VERSION}-dev
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
    volumes:
      - .:/app:rw
