services:
  netbox-devcontainer:
    image: netbox-devcontainer:dev-${VERSION}
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
    volumes:
      - .:/app:rw
